Set CONFIG_MAX_ZONEORDER to 9 on ppc64 with 64K pages
The previous setting of 13 caused build errors:

	In file included from include/linux/topology.h:32:0,
                 from include/linux/sched.h:78,
                 from arch/powerpc/kernel/asm-offsets.c:17:
	include/linux/mmzone.h:961:2: error: #error Allocator MAX_ORDER exceeds SECTION_SIZE
	make[1]: *** [arch/powerpc/kernel/asm-offsets.s] Error 1