cherry-pick from fedora all 3.17 changes before 3.18 as prepare to build new pf-kernel
$ git cherry-pick originFedora/f21 9b4c496b180a73d5f9be065691942f6e9a1df36a..dca3c158ea1942845f8d148e06bf13908574959d
error: could not apply 0802f28... Add various UAS quirks (rhbz 1124119)
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'

Add various UAS quirks (rhbz 1124119)

Conflicts:
	kernel.spec
	x86-vdso-Use-asm-volatile-in-__getcpu.patch

 It looks like you may be committing a cherry-pick.
 If this is not correct, please remove the file
	.git/CHERRY_PICK_HEAD
 and try again.