Fix bad variant usage in kernel dependencies
This was resulting in a variant build with dependencies like so:

error: Failed dependencies:
	kernel--vanilla-core-uname-r = ...

The variant already has a - at the start of it, so the always-there one
should be after variant and variant will provide the one between kernel
and itself.

Signed-off-by: Jarod Wilson <jarod@redhat.com>