Disable the BFA driver on ARM
It doesn't make much sense, and it fails to build because of a udelay(10000)
in it resulting in:

ERROR: "__bad_udelay" [drivers/scsi/bfa/bfa.ko] undefined!
make[1]: *** [__modpost] Error 1
make: *** [modules] Error 2
+ exit 1